### PR TITLE
[Reference] Add server command prompt with server command API

### PR DESCRIPTION
**Pull request by mhsjlw**
Example of adding a command-prompt to dazed-sheep using the flying-squid command API

### CODE REVIEW

**Comment by rom1504** [comment]
very flying-squid much copy-paste :p 
It's okay but eventually it would be better to somehow put that command system in an independent package.

**Comment by mhsjlw** [comment]
ah, flying-squid has this? I was actually completely unaware of that. I just thought of a quick way to hack it together, it's unlikely i'll merge this at the moment as it's more of a hack.

**Comment by rom1504** [comment]
I meant this https://github.com/dazed-sheep/dazed-sheep/pull/17/files#diff-4e492e4e1b14c827979d04d06a34c2b1R257

**Comment by mhsjlw** [comment]
@rom1504 :smile:

**Comment by mhsjlw** [comment]
This won't be merged as it's not optimal. Will be kept for reference though.

**Pull request closed without merging**
